/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Chart: typeof import('./../components/Chart/index.vue')['default']
    DailyAndMonth: typeof import('./../components/DailyAndMonth/index.vue')['default']
    DataTable: typeof import('./../components/DataTable/index.vue')['default']
    Detail: typeof import('./../components/Detail/index.vue')['default']
    Download: typeof import('./../components/Download/index.vue')['default']
    DownloadSuccessDialog: typeof import('./../components/DownloadSuccessDialog/index.vue')['default']
    FastTimeChoose: typeof import('./../components/FastTimeChoose/index.vue')['default']
    Form: typeof import('./../components/Form/index.vue')['default']
    GaugeBoard: typeof import('./../components/gaugeBoard/index.vue')['default']
    Icon: typeof import('./../components/Icon/index.vue')['default']
    ImportFile: typeof import('./../components/ImportFile/index.vue')['default']
    Loading: typeof import('./../components/Loading/index.vue')['default']
    Modal: typeof import('./../components/Modal/index.vue')['default']
    NavBack: typeof import('./../components/NavBack/index.vue')['default']
    NButton: typeof import('naive-ui')['NButton']
    NCheckbox: typeof import('naive-ui')['NCheckbox']
    NConfigProvider: typeof import('naive-ui')['NConfigProvider']
    NDialogProvider: typeof import('naive-ui')['NDialogProvider']
    NEl: typeof import('naive-ui')['NEl']
    NImage: typeof import('naive-ui')['NImage']
    NInput: typeof import('naive-ui')['NInput']
    NInputNumber: typeof import('naive-ui')['NInputNumber']
    NLoadingBarProvider: typeof import('naive-ui')['NLoadingBarProvider']
    NMenu: typeof import('naive-ui')['NMenu']
    NMessageProvider: typeof import('naive-ui')['NMessageProvider']
    NNotificationProvider: typeof import('naive-ui')['NNotificationProvider']
    NRate: typeof import('naive-ui')['NRate']
    NScrollbar: typeof import('naive-ui')['NScrollbar']
    NSlider: typeof import('naive-ui')['NSlider']
    NSpace: typeof import('naive-ui')['NSpace']
    NSwitch: typeof import('naive-ui')['NSwitch']
    PreAndToday: typeof import('./../components/PreAndToday/index.vue')['default']
    Preview: typeof import('./../components/Preview/Preview.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SaleCity: typeof import('./../components/SaleCity/index.vue')['default']
    Select: typeof import('./../components/Select/index.vue')['default']
    UploadBase64: typeof import('./../components/UploadBase64/index.vue')['default']
  }
}
